const DHome = () => {
  return (
    <div>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
      <h1>chart</h1>
    </div>
  );
};

export default DHome;
